services:
  neo4j:
    image: neo4j:5.22
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/test12345
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1g
      NEO4JLABS_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
